version: '3'
services:
  self-deployed-api:
    image: node:18
    container_name: mongo_search_self_deployed_api
    volumes:
      - ./self-deployed-api.ts:/self-deployed-api.ts
      - ./util.ts:/util.ts
      - ./node_modules:/node_modules
      - ./tsconfig.json:/tsconfig.json
      - ./package.json:/package.json
    ports:
      - 3000:3000
    command: npx ts-node self-deployed-api.ts
    env_file: .env.local
    environment:
      - MONGODB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongo_search_mongodb
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

  atlas-api:
    image: node:18
    container_name: mongo_search_atlas_api
    volumes:
      - ./atlas-api.ts:/atlas-api.ts
      - ./util.ts:/util.ts
      - ./node_modules:/node_modules
      - ./tsconfig.json:/tsconfig.json
      - ./package.json:/package.json
    ports:
      - 3001:3001
    command: npx ts-node atlas-api.ts
    env_file: .env.atlas
    depends_on:
      - mongodb
